### ISSUE TITLE
Determine SQL Trigger to increase book stock

### ISSUE THREAD

**Issue by nwarsalee** [COMP3005A-Project/bookstore#57]
Need to add a trigger in the SQL DDL statements to increase the book stock when supply gets under certain number
> The application should also be able to automatically place orders for new books if the remaining quantity is less than a given threshold (e.g., 10 books).

**Comment by hadicheaito1** [comment]
Random value between 5 and 15

**Comment by nwarsalee** [comment]
Trigger SQL statements known. Just need to implement them into the .sql files.
