### ISSUE TITLE
Create proper Github README

### ISSUE THREAD

**Issue by BoxThatBeat** [COMP3005A-Project/bookstore#7]
From the assignment:
All your source code for your application should be uploaded to a public GitHub repository. The code needs
to be well-documented and a decent README file that clearly states the instructions for running your code
should be provided. The GitHub repository should also include a directory titled “SQL” that includes all the
SQL DDL statements and SQL queries used in your application. You can organize the files in this directory
in whichever way you would like. But all the files should have the .sql extension. For example, the directory
“SQL” could have four files “DDL.sql”, “Functions.sql”, “Triggers.sql”, and “Queries.sql”. The files should be
well-documented using comments in SQL (e.g., purpose of trigger, what a query retrieves from the database,
etc.). This section should include the url to this GitHub repository.

**Comment by nwarsalee** [comment]
In PR #11 I made a general skeleton for our readme. Has packages/dependency list, headers for description, instructions, project info and assumptions. These can be filled out as we go with the development. I'll create separate issues for those so we don't forget
